using Saku_Overclock.Helpers;

namespace Saku_Overclock.Models;
public class Preset
{  
    public string PresetName = "Param_UnsignedPreset".GetLocalized();
    public string PresetDesc = "";
    public string PresetIcon = "\uE718";
    public string PresetId = Guid.NewGuid().ToString().Remove(8);
    public AutoGeneratedType GeneratedType = AutoGeneratedType.Custom;
    public bool AdaptiveAdjustment = false;
    
    // CPU configuration
    public PresetCpuSettings CpuSettings { get; init; } = new();
    
    // VRM configuration 
    public PresetVrmSettings VrmSettings { get; init; } = new();
    
    // iGPU and CPU subsystems configuration
    public PresetSubsystemsSettings SubsystemsSettings { get; } = new();
    
    // Advanced options configuration 
    public PresetAdvancedCpuModesSettings CpuModesSettings { get; init; } = new();
    
    // Curve Optimizer configuration
    public PresetCurveOptimizerOptions CurveOptimizerOptions { get; init; } = new();
    public PresetCurveOptimizerAdvancedOptions CurveOptimizerAdvancedOptions { get; init; } = new();
    
    // Frequencies settings
    public PresetFrequenciesSettings FrequenciesSettings { get; } = new();
    
    // Send custom SMU commands configuration
    public bool DebugSmuCommandsSend = false;
    
    // Override SMU Functions configuration
    public PresetSmuFeaturesSettings SmuFeaturesSettings { get; } = new();
}